spring:
  jwt:
    secret: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb"

  datasource:
    url: jdbc:mysql://mysql:3306/mycommunity?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mycommunity
    password: Mycommunity2024!@#

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  h2:
    console:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379
      # password: "your_redis_password" # Uncomment and set if Redis requires a password